### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Kelzor** [TCLamnidis/Sex.DetERRmine#10]
I get the following error that breaks the pipeline when running --run_sexdetermine v1.1.2 on nf-core/eager v2.4.5 on a shallow sequencing SG library. 

Attached is the full slurm output. A quick grep of the bam returns >400 reads mapping to the Y chromosome, but I suspect they do not pass the Sex.DetERRmine QC?

```
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/eager] Pipeline completed with errors-
Error executing process > 'sexdeterrmine'

Caused by:
  Process `sexdeterrmine` terminated with an error exit status (1)

Command executed:

  ls *.bam >> bamlist.txt
  samtools depth -aa -q30 -Q30  -f bamlist.txt | sexdeterrmine -f bamlist.txt > SexDet.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-eager-2.4.5/bin/sexdeterrmine", line 111, in <module>
      rate,rateErr=CalcErrors(AutSnps, XSnps, YSnps, NrAut[Names[Ind]], NrX[Names[Ind]], NrY[Names[Ind]])
    File "/opt/conda/envs/nf-core-eager-2.4.5/bin/sexdeterrmine", line 27, in CalcErrors
      dp[Bin]=Reads[Idx]/SNPs[Idx]
  ZeroDivisionError: division by zero

Work dir:
  /nobackup/zsbx26/eager-outputs/talbot-sex-13-10-22/work/b0/a5aa6066326dffb8e273eb8ae1847f

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

[slurm.2054369.txt](https://github.com/TCLamnidis/Sex.DetERRmine/files/9784750/slurm.2054369.txt)

**Comment by carolinaevapadilha** [comment]
I also got this issue related to sex determination:

```
nf-core/eager execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'sexdeterrmine'

Caused by:
  Process `sexdeterrmine` terminated with an error exit status (1)

Command executed:

  ls *.bam >> bamlist.txt
  samtools depth -aa -q30 -Q30 -b 1240K.pos.list_hs37d5.0based.bed -f bamlist.txt | sexdeterrmine -f bamlist.txt > SexDet.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-eager-2.4.7/bin/sexdeterrmine", line 111, in 
      rate,rateErr=CalcErrors(AutSnps, XSnps, YSnps, NrAut[Names[Ind]], NrX[Names[Ind]], NrY[Names[Ind]])
    File "/opt/conda/envs/nf-core-eager-2.4.7/bin/sexdeterrmine", line 31, in CalcErrors
      rate[Bin]=dp[Bin]/dp["Aut"]
  ZeroDivisionError: float division by zero

Work dir:
  /mnt/archgen/users/carolina_padilha/eager/brasilsamples/work/21/be1fa9baa1525260e5c2db3249afff

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```
